version: '3'
services:
  nextjs:
    build: .
    container_name: nextjs
    restart: unless-stopped
  
  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    ports:
      - "${DOCKER_NGINX_PORT}:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - nextjs